// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9hA39KtYg3BevSMNGZjo8u
// Component: Q-X2qK66L2
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_bbeats.module.css"; // plasmic-import: 9hA39KtYg3BevSMNGZjo8u/projectcss
import * as sty from "./PlasmicSearchbar.module.css"; // plasmic-import: Q-X2qK66L2/css

export type PlasmicSearchbar__VariantMembers = {};

export type PlasmicSearchbar__VariantsArgs = {};
type VariantPropType = keyof PlasmicSearchbar__VariantsArgs;
export const PlasmicSearchbar__VariantProps = new Array<VariantPropType>();

export type PlasmicSearchbar__ArgsType = {};
type ArgPropType = keyof PlasmicSearchbar__ArgsType;
export const PlasmicSearchbar__ArgProps = new Array<ArgPropType>();

export type PlasmicSearchbar__OverridesType = {
  root?: p.Flex<"input">;
};

export interface DefaultSearchbarProps {
  className?: string;
}

function PlasmicSearchbar__RenderFunc(props: {
  variants: PlasmicSearchbar__VariantsArgs;
  args: PlasmicSearchbar__ArgsType;
  overrides: PlasmicSearchbar__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <input
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.input, projectcss.root_reset, sty.root)}
      placeholder={"Some placeholder" as const}
      size={1 as const}
      type={"text" as const}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSearchbar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicSearchbar__VariantsArgs;
  args?: PlasmicSearchbar__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicSearchbar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicSearchbar__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSearchbar__ArgProps,
      internalVariantPropNames: PlasmicSearchbar__VariantProps
    });

    return PlasmicSearchbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSearchbar";
  } else {
    func.displayName = `PlasmicSearchbar.${nodeName}`;
  }
  return func;
}

export const PlasmicSearchbar = Object.assign(
  // Top-level PlasmicSearchbar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSearchbar
    internalVariantProps: PlasmicSearchbar__VariantProps,
    internalArgProps: PlasmicSearchbar__ArgProps
  }
);

export default PlasmicSearchbar;
/* prettier-ignore-end */
